### ISSUE TITLE
グループやユーザ名を呼んで、リマインドしてあげると優しい。

### ISSUE THREAD

**Issue by pokohide** [kentosasa/rima_bot#100]
「xxさん、リマインドを設定しますか？」みたいな

**Comment by kentosasa** [comment]
グループ名は長いことがあるからこの機能が実際にあるとめんどくさそう。

例えば
「劇団EnTRoPy 2016幹部LINEさん、リマインドを設定しますか？」

みたいになるとちょっと邪魔なる気がする

**Comment by pokohide** [comment]
user_typeがユーザのときだけ、呼びかけても良いかもねー。
グループだと誰の名前でもないから、呼びかけても鬱陶しいだけだねｗ
