### ISSUE TITLE
広告を消すなら、予定の通知はカルーセルでなくてもいいかも。位置情報もないから画像もいらないからもっとシンプルにできる

### ISSUE THREAD

**Issue by pokohide** [kentosasa/rima_bot#103]

**Comment by kentosasa** [comment]
位置情報はIPからとってくるんじゃなかったっけ？

そもそも天気通知とかの機能含めて削除する？？

**Comment by pokohide** [comment]
あー、天気の画像を返すかどうかは、ちょい検討したいな

IPから位置情報を取ってくる = どのリマインドにも位置情報が付与される
-> 今の仕様だと天気を表示する対象になる
-> 全てのリマインドに天気情報が付与される

これを画像にするのは何か重たい気がするから、やるならその日が雨なら

---
飲み会 ☂ 1℃
明日の10時にどこどこ集合ね～
---

みたいに絵文字で天気を表示したいかな！！画像だとやっぱり縦長すぎる気がする。カルーセルにすると特に個人的に圧迫感があった

**Comment by kentosasa** [comment]
なるほ。確かに圧迫感はあった。。。
関連場所推薦がないならButtonだけでいいかも

ちなみに全てのリマインドが位置情報をとれるわけではないぞい。
LINE内で通知まですべてやった場合は位置情報はとれない。

**Comment by pokohide** [comment]
> LINE内で通知まですべてやった場合は位置情報はとれない。

そうだった。
それと、今だとpostbackで通知をONとかしてたけど、これだとPOSTっぽく実装出来てキレイだけど、グループ上では誰が通知をONにしたかがわからないから、ボタンを押したら文字を自動で文字を送信して、それを読み取って、通知をONにするとかしたら、誰が通知をONにしたかとかがわかりそう

ただこれのせいでグループが荒れる可能性も含んでるから、今のままのほうが良さげではあるか

**Comment by kentosasa** [comment]
> ボタンを押したら文字を自動で文字を送信して

1.URI Action で必ず一度Webに遷移するようにするってこと？
2.Message Actionを使うということ？

1はLINEらしさがなくなるし、2.結局web遷移しないからIPとれないので
基本は今の使用でいいのではないかなぁ

天気は間違った情報きたらイラッと来るのでdefaultで位置情報つけるとかは無しで、なければ天気関連の情報は返さないというのが自然な気がする。
