### ISSUE TITLE
「通知を取り消す」の内部的処理はどうする？そのリマインドを無効＝廃棄にするか？

### ISSUE THREAD

**Issue by pokohide** [kentosasa/rima_bot#109]

**Comment by kentosasa** [comment]
あるのが理想ではある。けど中身がこんがらがるなら要らない部分。

remindのatがnilになっているのが意味的には理想な気がするけど、今までのメソッドがnilを想定してない気がする。

remindedをtrueにするか、atを 9999年12月31日とかにするのがいいのかなぁ

**Comment by kentosasa** [comment]
- [ ] イベント削除
- [ ] at <= nil
- [ ] reminded <= true
- [ ] at <= 9999y12m31d

**Comment by pokohide** [comment]
`nil` を含むのは怖いから、（`nil`は悪）やるなら

is_public: そのリマインドの存在
is_activeted: そのリマインドが有効化
is_notified: そのリマインドが通知済みか

の3つのカラムにするか、
status: integer [CREATED, ACTIVATED, NOTIFIED]
みたいな3状態をenumで管理するかどうかしたいな

**Comment by kentosasa** [comment]
statusにしよう

```xxxx.active.pending.around```
みたいにするのが気持ち悪いとおもってたところだからちょうどいい

**Comment by pokohide** [comment]
migrateするのとかはマージ注意ラベル付与した

**Comment by kentosasa** [comment]
いい話だ。
わかりやすくて助かります。
