### ISSUE TITLE
スケジュールの人数(String)はIntegerにするか消していいんじゃないか説

### ISSUE THREAD

**Issue by pokohide** [kentosasa/rima_bot#110]

**Comment by kentosasa** [comment]
その通りですね。
設計時はintegerだった気がするので、僕のミスな気がします。。。。

ごめんなさい

**Comment by kentosasa** [comment]
回答期限に達してなければ通知をONにするみたいなのは複雑な機能な気がしてきた

削除の方針で行こうと思うのですが、どうですか？

**Comment by pokohide** [comment]
まぁ本来これはユーザに入力してもらうべき箇所ではないから、LINE BOTでグループ人数が取れるようにバージョンアップすることを祈ろうってことで、削除しましょう
