### ISSUE TITLE
webの / をプレスリリースページにする

### ISSUE THREAD

**Issue by kentosasa** [kentosasa/rima_bot#111]
動画とか簡単な使い方とかスクショとかのせる

**Comment by pokohide** [comment]
今rootが何も割り当てられてないから、そこに割り当てよっか

https://templated.co/

**Comment by pokohide** [comment]
- https://html5up.net/stellar
- https://html5up.net/fractal
- https://html5up.net/read-only

こんな感じのサイトにしたいね。

リマさんのコンセプトと、このリリースページのシェアボタン(fb, tw)、リマの特徴3つと、最後にContact us

**Comment by kentosasa** [comment]
よいねえ
その３つの中なら最初のが１番印象に近いかも

topのロケットの代わりにLine Icon使えるし

でもここでスタイリッシュな感じで見せるならならLINEのiconもwebの方に統一したいな

**Comment by kentosasa** [comment]
https://line.me/ja/
LINEのHPがいい感じ

**Comment by kentosasa** [comment]
超かっこよくなっててビビった

**Comment by kentosasa** [comment]
調整してみたから確認してみてー！
