### ISSUE TITLE
READMEをちゃんと作る

### ISSUE THREAD

**Issue by pokohide** [kentosasa/rima_bot#113]
開発者とか、BOTの概要とかバグ修正の場合は、フォークしてbugブランチ切ってプルリク出すとか、そういったREADMEに更新する。また、dockerでのセットアップ方法などまとめる

**Comment by kentosasa** [comment]
せやね！
LINEもエンジニア集団だし、そういう開発体制は好まれる気がする。

もしかしたらプルリクくるかもしれないしな笑
