### ISSUE TITLE
google analyticsを入れる

### ISSUE THREAD

**Issue by kentosasa** [kentosasa/rima_bot#115]
活用度とかの数字をとっといて、資料に入れたい

**Comment by pokohide** [comment]
サーバーサイドでどれくらいのメッセージのやりとりをしたかとかは、LINEの管理ページで確認できるんだよね？

WEBの方はそれで集計しようか！
あとGroupの数 = 使ってもらった数だから、多分これは管理画面の方でも集計はできないよね？友達の数は取れるけど
