### ISSUE TITLE
日付候補日は編集できるようにする？

### ISSUE THREAD

**Issue by pokohide** [kentosasa/rima_bot#120]
出来ないほうがいいような気もする。

もし、できるようにするなら、編集時に最後尾に何もない改行が含まれるのを修正

**Comment by kentosasa** [comment]
調整さんは一応できるけど、どうなんだろうか。

あんまり使う機能ではないので今回は要らない気がするなぁ

**Comment by pokohide** [comment]
日程の調整は出来ないようにしようか！また、対応する
