### ISSUE TITLE
日程調整時にコメントもできるように

### ISSUE THREAD

**Issue by pokohide** [kentosasa/rima_bot#126]

**Comment by kentosasa** [comment]
これは日程調整関連のモデル構成を修正するときに一緒に組み込んだほうが良さそうですね

**Comment by kentosasa** [comment]
あるいは
Comment
- schedule_id
- user_id
- text

を作れば既存のでも作成できなくはないかな

**Comment by pokohide** [comment]
ユーザ一人に対して、コメントは一つだろうから、やるなら、Userモデルにcommentカラムをtextで追加するほうがキレイかな！

**Comment by kentosasa** [comment]
それだと将来ユーザーアカウントを作って、
ユーザーを使いまわすときに問題が出てくるなと思った。

ただ、どうせ今回はどうせしないから問題ないか！！！（）
