### ISSUE TITLE
良さげなBGMを探す

### ISSUE THREAD

**Issue by kentosasa** [kentosasa/rima_bot#135]

**Comment by kentosasa** [comment]
現状のは著作権上問題あるので音問題を解決する。
邦楽なら大丈夫という話もあったけど、CC- BGMが集まったサイトを映像に強い人に教えてもらったのでそれを使う。

- https://www.youtube.com/audiolibrary/music
- https://www.jamendo.com/
- https://www.extrememusic.com/

**Comment by kentosasa** [comment]
暫定これ
http://dova-s.jp/bgm/play5842.html

**Comment by pokohide** [comment]
https://www.extrememusic.com/
このサイト気に入ったわｗ

作業用BGMとして使う（笑）
いいのあったら、また共有するーー！
