### ISSUE TITLE
動画に出てくれる学生の確保

### ISSUE THREAD

**Issue by kentosasa** [kentosasa/rima_bot#136]
１人は口約束で確保
スケジュール調整中

もう1人は火曜夜に撮影の約束取り付けた

**Comment by kentosasa** [comment]
残りは俺とひでとかでいいかなと思ってる

**Comment by pokohide** [comment]
@kentosasa 今週の土日で良いなら、Skypeとかしながら、グループ作ってやろっか！

**Comment by kentosasa** [comment]
日曜やりたいな！
