### ISSUE TITLE
動画の確認作業

### ISSUE THREAD

**Issue by kentosasa** [kentosasa/rima_bot#140]
大体できた。
あとはひでの埋め込みと、スキーのパンフレット見てる部分に置き換えて終了の予定。

気になる所あれば修正するので確認お願い！
@hyde2able 

https://drive.google.com/file/d/0B2NH76GIV6teTVNCcHVNVnNvblk/view?usp=sharing

**Comment by pokohide** [comment]
@kentosasa 27秒くらいのとこで、リマインドを設定したらリマさんから、リマインドを設定しましたーって来るとこがないから、何かちょっとわかりづらいかなー。

この部分は前の動画の時みたいに、リマさんの設定しましたーって一言が会ったほうが何か好き

**Comment by kentosasa** [comment]
動画の新しいBGMこれはどうかな？
https://drive.google.com/file/d/0B2NH76GIV6teSzczYXRIamVRSzA/view?usp=sharing
時間も短くなってるのでこれに合わせてLINEのところの再生速度を上げればテンポは上がりそう。

あと、OPのanimationできたぞい
https://www.youtube.com/edit?o=U&video_id=2o4Cx-MmUQU

明日にリリースできるようにするぞ〜〜

**Comment by kentosasa** [comment]
この曲で作り直しちゃうね！

**Comment by kentosasa** [comment]
https://www.youtube.com/watch?v=4w7IwoGe7Lo

終わったああああああ。
問題なければこれで終わり！！

**Comment by kentosasa** [comment]
てかインターンの動画著作権侵害申請きててワロタ

**Comment by pokohide** [comment]
@kentosasa 気づかなかったｗ
前の曲よりは好きｗ
見てて遅いなーって感じなかったから良いと思う！！ありがとうー！
