### ISSUE TITLE
botの機能概要 (最大1200文字)

### ISSUE THREAD

**Issue by kentosasa** [kentosasa/rima_bot#142]
コンテストに登録するのに必要なので作成する

[概要]
簡単に予定を立てて、グループ全体に通知してくれるリマインドBot

[機能]
- 予定の作成とリマインド
- イベントの出欠などをする日程調整

[使い方]
LINEグループにリマさんを招待して普段通りに友達と予定を立てるだけで予定の作成を提案してくれます。
「じゃあ明日の５時に新宿集合ね！」
「いつにしよっか〜」
などの予定が決まったタイミングや日程調整が必要なタイミングになるとリマさんが予定作成の提案をしてくれます。
そのほかにもリマさんに
「今日の予定はなんだっけ？」
と質問すると作成された予定を教えてくれます。

[便利な点]
従来ではLINE上で予定ができた後にリマインドを設定するためにはカレンダーアプリやスケジュールアプリなどの別のアプリを開く必要がありました。このBotを使うとアプリ間の移動無く簡単に予定のリマインドをすることができます。
また、予定を作成する際に一度でも詳細画面を開いた場合はリマインドする際に予定日の天気と温度も同時に知らせてくれるなどの機能がついています。

[開発上こだわった点]
Botの持つ違和感をなくすことに注視しました。
今回こだわったのは
「特別な入力コマンドを作らない」
という点です。
「>リマさん 2016/08/11/12/15」
のようなコマンドベースの入力をユーザーに要求するのは簡単ですが、それでは女子高生や普通の友達は使わないだろうということで日常会話から予定入力を受け付けるようにしました。
仕組みとしては自然言語から日時を抽出する自作ライブラリ Datte*1 を利用し、会話の中に日時が含まれていてネガティブワードを含まない場合のみ予定の提案をするようにしています。

[今後の展望]
WEB上の詳細画面に広告を配置することでマネタイズを図ります。
ユーザー数を確保できたあとは飲食店やレジャー施設との連携を行い、
予定のリマインドをする際に同時に近辺の飲食店やイベントの情報をリマインドをしていきます。

**Comment by kentosasa** [comment]
落合陽一のバリバリ研究論文が読めるまとめ方とやらを参考にしてみる

どんなもの？
先行研究と比べてどこがすごい？
技術や手法のキモはどこ？
どうやって有効だと検証した？
議論はある？
次に読むべき論文は？


今回は以下のフォーマットでまとめる

どんなもの？
なにができるの？
使い方は？
先行事例と比べてどこがすごい？
技術や手法のキモはどこ？
このあとどうなるの？

**Comment by kentosasa** [comment]
気になるところがあったら編集しちゃってほしいな
@hyde2able

**Comment by masui** [comment]
研究なの?

**Comment by kentosasa** [comment]
違います。このフォーマットに則ってつくればわかりやすく伝えられそうだなと思ったので。
