### ISSUE TITLE
urlにidを表示すると簡単に他の人のリマインドを覗く、編集することができてしまう

### ISSUE THREAD

**Issue by kentosasa** [kentosasa/rima_bot#53]
Web側でURLのところにremind_idが表示されている
現状だと自分のIdを少し書き換えるだけで他の人のリマインドを覗けてしまう

思いつく解決法
- リマインドにpath:stringみたいなカラムを作ってそれをurlに表示する
- データ作成時にリマインドidに乱数が入るようにする。
- ユーザーに見せる部分だけidを暗号化するようにする。

**Comment by kentosasa** [comment]
開発コスト的には
「データ作成時にリマインドidに乱数が入るようにする」
が１番楽そうだけどどれがいいかな？
@hyde2able

**Comment by pokohide** [comment]
uidというカラムを持たせてそれをSecureRandomでハッシュ値を生成してそれでアクセスするようにした-!
