### ISSUE TITLE
Herokuで代用するがドメインは独自ドメインにする

### ISSUE THREAD

**Issue by pokohide** [kentosasa/rima_bot#93]
http://www.sakagami3.com/entry/2016/07/10/161814

**Comment by pokohide** [comment]
rima-san.me
は取得

**Comment by pokohide** [comment]
めんどくさそう(´・ω・｀)

**Comment by kentosasa** [comment]
herokuデフォルトドメインは検索に引っかからない印象があるのだがどうなのだろうか
流石にリマさん botとかで調べたら出てきて欲しい気がする

動かすだけならVPSでも問題ない気がするがherokuのメリットはなんなんだろう

**Comment by pokohide** [comment]
@kentosasa 

基本的に普通のページのnoindexにするから、検索に出ちゃいけない部分で、そのかわりプレスリリースの方のメタタグとかちゃんとすれば、それだけで引っかからせることはできるかな！

「ついまな」ってサービスとか、Herokuに載せてるけど普通に検索には出てくる(・∀・)ｂ

**Comment by kentosasa** [comment]
なるほ！ならいいか！
