### ISSUE TITLE
PVの修正

### ISSUE THREAD

**Issue by pokohide** [kentosasa/rima_bot#96]

**Comment by kentosasa** [comment]
そんな可愛いわけではないけど、女子大生は１人確保した。

LINE部分は本当にガッツリ時間取ってもらわないと厳しいから家族つかって取り直すかも。

**Comment by kentosasa** [comment]
BGMが無許可利用の現在の仕様はまずいので、知り合いの映像仕事にしてる人に良さげなBGM入手法きいてみます。

**Comment by pokohide** [comment]
> そんな可愛いわけではないけど、女子大生は１人確保した。

ｗｗありがとう！！

**Comment by pokohide** [comment]
> BGMが無許可利用の現在の仕様はまずいので、知り合いの映像仕事にしてる人に良さげなBGM入手法きいてみます。

まだちゃんと調べてないけど、洋楽は基本的にその洋楽を管理してるところに連絡をして使っていいかを聞くらしいけど、相場は1曲10万~ くらいらしい。

それに比べて邦楽はJASRACが管理してて、もし非商用でJASRACが承諾しているサイト内(Youtubeとか)でなら、使っても良い　みたいな記述を見つけたから

- 邦楽(JASRAC)で良いのを見つける
- 誰かに演奏してもらう
- フリーで見つける

になると思うけど、一番上が現実性高そうだね

**Comment by kentosasa** [comment]
> それに比べて邦楽はJASRACが管理してて、もし非商用でJASRACが承諾しているサイト内(Youtubeとか)でなら、使っても良い　みたいな記述を見つけたから

まじか！！ソースが欲しいかも！

premireとかにもデフォで幾つかBGM入ってた気がするから今度聞いてみるわ

**Comment by pokohide** [comment]
http://www.jasrac.or.jp/info/

**Comment by pokohide** [comment]
他のISSUEとかぶっている感じがするので、一旦クローズ
